use_frameworks!

platform :ios, '9.0'

target 'ORFileDownloader_Example' do
  pod 'ORFileDownloader', :path => '../'

  target 'ORFileDownloader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
